"""Utility modules for Depth Surge 3D.

Re-exports all utility modules for backward compatibility.
"""

# System utilities
from .system import (
    get_available_vram,
    get_total_vram,
    estimate_frame_vram_usage,
    calculate_optimal_chunk_size,
    get_vram_info,
    success,
    error,
    warning,
    info,
    dim,
    title_bar,
    step_complete,
    saved_to,
    completion_banner,
)

# Domain utilities
from .domain import (
    get_cache_dir,
    compute_cache_key,
    get_cached_depth_maps,
    get_cached_depth_map_files,
    save_depth_maps_to_cache,
    save_depth_map_files_to_cache,
    clear_cache,
    get_cache_size,
    parse_custom_resolution,
    get_resolution_dimensions,
    calculate_vr_output_dimensions,
    calculate_aspect_ratio,
    classify_aspect_ratio,
    auto_detect_resolution,
    get_format_recommendation,
    validate_resolution_settings,
    get_available_resolutions,
    ProgressReporter,
    ConsoleProgressReporter,
    ProgressTracker,
    ProgressCallback,
    create_progress_tracker,
    calculate_eta,
    format_time_duration,
)

# Imaging utilities
from .imaging import (
    resize_image,
    validate_image_array,
    calculate_image_statistics,
    normalize_depth_map,
    depth_to_disparity,
    create_shifted_image,
    hole_fill_image,
    apply_center_crop,
    calculate_fisheye_coordinates,
    apply_fisheye_distortion,
    apply_fisheye_square_crop,
    create_vr_frame,
    process_video_serial,
    process_video_batch,
)

__all__ = [
    # System utilities
    "get_available_vram",
    "get_total_vram",
    "estimate_frame_vram_usage",
    "calculate_optimal_chunk_size",
    "get_vram_info",
    "success",
    "error",
    "warning",
    "info",
    "dim",
    "title_bar",
    "step_complete",
    "saved_to",
    "completion_banner",
    # Domain utilities
    "get_cache_dir",
    "compute_cache_key",
    "get_cached_depth_maps",
    "get_cached_depth_map_files",
    "save_depth_maps_to_cache",
    "save_depth_map_files_to_cache",
    "clear_cache",
    "get_cache_size",
    "parse_custom_resolution",
    "get_resolution_dimensions",
    "calculate_vr_output_dimensions",
    "calculate_aspect_ratio",
    "classify_aspect_ratio",
    "auto_detect_resolution",
    "get_format_recommendation",
    "validate_resolution_settings",
    "get_available_resolutions",
    "ProgressReporter",
    "ConsoleProgressReporter",
    "ProgressTracker",
    "ProgressCallback",
    "create_progress_tracker",
    "calculate_eta",
    "format_time_duration",
    # Imaging utilities
    "resize_image",
    "validate_image_array",
    "calculate_image_statistics",
    "normalize_depth_map",
    "depth_to_disparity",
    "create_shifted_image",
    "hole_fill_image",
    "apply_center_crop",
    "calculate_fisheye_coordinates",
    "apply_fisheye_distortion",
    "apply_fisheye_square_crop",
    "create_vr_frame",
    "process_video_serial",
    "process_video_batch",
]
